[package]
name = "photon_chicken"
version = "0.1.0"
authors = ["Nico Hickman <nicohman@protonmail.com>"]

[dependencies]
piston = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
pistoncore-glutin_window = "*"
rand = "*"
gilrs = "*"
